title: Ramathibodi Digital Health Academy
author: คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี
logo: assets/dha-logo.svg

execute:
  execute_notebooks: "off"

html:
  extra_css:
    - assets/carbon.css
    - assets/dha-overrides.css
